### ISSUE TITLE
SVG Export

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#121]
**Describe the solution you'd like**
The ability to export all paths on the active frame as an SVG file.

**Comment by olivetthered** [comment]
I'll do this as soon as import is finalised. should be a relatively quick change to start with.

**Comment by olivetthered** [comment]
I think this can be done by creating a paper group of all layers on the timeline merging path and clip layers. then calling exportSVG on the group or the first layer in the group if there is only one layer.

**Comment by olivetthered** [comment]
I'm tempted to put the code for this in Base so that the project, clips, selections and pretty much any object can easily be exported to SVG. I don't believe clips and selections are exportable to anything at the moment so this is a bit future thinking. it looks like the project class only allows for children that are actually part of the drawing as opposed to the view.project class that also has elements of the GUI embedded in it.

yes project base is just a Wick.Clip(), so I can write some code in clip to export to SVG (as that's a nice to have) and have p[roject express a wrappewr to that.

**Comment by olivetthered** [comment]
it ended up in the timeline class due to the mixture of frames and layers being appropriate there.
I've got exportingSVG at playheadPosition almost compete and I will be testing it soon. it currently bundles everything into a nice paper.Group then calles ExportSVG on that paper Group and tidies up

**Comment by olivetthered** [comment]
almost there with this now. just iterating over clips to do and finding out how to get the root node to be svg instead of g because nothing likes the svg in the file unless I change the root node from g to svg.

**Comment by olivetthered** [comment]
it's anoying that debugging isn't easier. visual studio code is basically non functionsl if you load up the js script the engine is built to.

**Comment by olivetthered** [comment]
This is now working correctly and also simplified as it turns out calling exportSVG on the paper.project worked just fine.
<img width="1050" alt="2020-04-10 (2)" src="https://user-images.githubusercontent.com/37796246/78984998-97d8ec80-7b1f-11ea-9d3b-24e3c8dfb80b.png">

**Comment by olivetthered** [comment]
doesn't open in the current stable inkscape but opens just fine in inkscape 1.0 beta.

**Comment by olivetthered** [comment]
this is now 100% functional and ready to merge
