### ISSUE TITLE
[BUG] Quickly cycling through frames while drawing fast strokes can cause a "brush error".

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#131]
**Describe the bug**
Quickly drawing while cycling frames can cause the brush to "lock up" and stop drawing. This bug was found by Hyun and requires more investigation.

The project below has an explosion that causes the problem.

[My_Project1-19-2020_1-02-31PM.wick.zip](https://github.com/Wicklets/wick-editor/files/4083564/My_Project1-19-2020_1-02-31PM.wick.zip)

**Comment by Luxapodular** [comment]
After some attempted implementation, it looks like buffering changing the frame will require a significant refactor, so we are going to attempt another fix.

Steps:
1. Save a frame uuid to each drawn stroke.
2. Potrace that stroke
3. Add the stroke to the frame it was drawn on by uuid.
4. If the frame we are on changes, make sure to pause any future drawing until the potrace step is complete, to avoid the "doublestroke" error where multiple drawings on separate frames can be turned into the same drawing.

**Comment by zrispo** [comment]
This issue has been fixed in cf6a1f7ed767310a71739ac6466c1ad36963dd4c

Saving the `activeFrame` when brush strokes are first started and only adding the resulting path to that saved frame has fixed the issue where strokes could be added to the wrong frame.

Additionally, as soon as the playhead is moved in the editor, a new function called `finishStrokeEarly` is called, which discards the current drawing state and potraces the croquis canvas immediately.
