### ISSUE TITLE
[BUG] Eraser will erase multiple lines if those lines are small.

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#157]
**Describe the bug**
Small strokes can overlap the eraser incorrectly.

**Screenshots**

![gif](https://user-images.githubusercontent.com/8699557/76766274-1daa8780-676e-11ea-8c4a-e9361f03c251.gif)

**Comment by zrispo** [comment]
After some investigation, it turns out that the issue is with two or more brush strokes united together.

![erase-error](https://user-images.githubusercontent.com/4970417/76993103-b550d700-6922-11ea-8c7e-96d048cb662a.gif)

In the gif, two paths are united into a compound path. The child paths can be erased without issue, but trying to erase between the two child paths causes the entire compound path to be erased.
