### ISSUE TITLE
[BUG] Random.float() without parameters returns NaN

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#39]
**Describe the bug**
Passing no parameters to Random.float() returns NaN

**To Reproduce**
1. Select a frame within a Wick Project
2. Add the code `Random.float()` to the frame's default script.
3. Console log the result.

**Expected behavior**
This should return a random float between 0 and 1.

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**

This can be fixed within the `engine > src > GlobalAPI.js` file within the GlobalAPI.Random class!

**Comment by ComradeSparklePony** [comment]
I've basically got this sorted out, but there's a bit of an inconsistency with the already existing code which I'm not sure whether or not to emulate. Currently, `random.float(min, max)` has a range of [min, max+1) meaning that `random.float(0, 1)` can return `1.9`. This sort of behavior can make sense for integers because then it's just an inclusive range, but it's a bit confusing for floats; it sometimes generates a number above the maximum value.

I see 3 ways this can be dealt with (more ways could exist):
- Changing the behavior of `random.float(min, max)` so that doesn't generate above it's maximum value. (May break compatibility with existing projects, but works more intuitively because it's actually in the range)
- Write `random.float()` so that it generates numbers in the range [0,2)
- Leave the behavior of `random.float(min, max)` as is, but have `random.float` generate numbers in the range [0, 1).

What do you think?

I've also implemented a `random.float(max)` that generates a number in the range [0, max); although not explicitly requested in the issue description, I think it makes sense; just want to make sure it makes sense to others as well. If there's interest, I can extended `random.integer` in a similar way as well (and add a zero-argument `random.integer` for consistency).

Thank you!

**Comment by Luxapodular** [comment]
Oh this is great, thanks for reaching out about this issue.

I personally think that option 1 is best, as it should provide values from [min, max) (no [min, max+1) !, this is a bug!)

If you're interested in contributing, I'm happy to help with this implementation and work the change in through a Pull request!

**Comment by ComradeSparklePony** [comment]
I think I've got a decent implementation so far, but this is my first time contributing to a project that isn't my own; I think I know what to do with regards to a pull request, but if something comes up I'll let you know!

Should I update the behavior of `random.integer` so that it generates in the range [min, max), or should I leave it be so that it continues to be [min, max]?

Thank you for the help!

**Comment by ComradeSparklePony** [comment]
Here's what I've got so far: [https://github.com/ComradeSparklePony/wick-editor/commit/d6476279f4ab98a9de8f481009fd785e0dac3c70](https://github.com/ComradeSparklePony/wick-editor/commit/d6476279f4ab98a9de8f481009fd785e0dac3c70)

**Comment by Luxapodular** [comment]
Hey this is so great, and I really appreciate you updating the documentation tags! (You've done a phenomenal job here). 

Updating random.integer would be awesome if possible! Feel free to add those changes and then send over a pull request and I can get these in for 1.19!

**Comment by ComradeSparklePony** [comment]
Alright, how does it look? #289

**Comment by Luxapodular** [comment]
@ComradeSparklePony Looks great! Integrated for 1.19 in f416045c.
